channels:
- conda-forge
dependencies:
- python=3.8.8
- pip
- pip:
  - mlflow
  - cloudpickle==1.6.0
  - psutil==5.8.0
  - scikit-learn==0.0
  - scikit-learn==0.24.1
  - typing-extensions==3.10.0.2
name: mlflow-env
